export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_SAVE_SHIPPING_ADD = "CART_SAVE_SHIPPING_ADD";
export const CART_SAVE_PAYMENT_TYPE = "CART_SAVE_PAYMENT_TYPE";
