export const ORDER_CREATE_REQ = "ORDER_CREATE_REQ"
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const ORDER_INFO_REQ = "ORDER_INFO_REQ";
export const ORDER_INFO_SUCCESS = "ORDER_INFO_SUCCESS";
export const ORDER_INFO_FAIL = "ORDER_INFO_FAIL";

export const ORDER_PAY_REQ = "ORDER_PAY_REQ";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const ORDER_USER_LIST_REQ = "ORDER_USER_LIST_REQ";
export const ORDER_USER_LIST_SUCCESS = "ORDER_USER_LIST_SUCCESS";
export const ORDER_USER_LIST_FAIL = "ORDER_USER_LIST_FAIL";
export const ORDER_USER_LIST_RESET = "ORDER_USER_LIST_RESET";

export const ORDER_LIST_REQ = "ORDER_LIST_REQ";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";