export const ORDER_CREATE_REQ = "ORDER_CREATE_REQ"
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const ORDER_INFO_REQ = "ORDER_INFO_REQ";
export const ORDER_INFO_SUCCESS = "ORDER_INFO_SUCCESS";
export const ORDER_INFO_FAIL = "ORDER_INFO_FAIL";

export const ORDER_PAY_REQ = "ORDER_PAY_REQ";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";