
export const PROD_LIST_REQ = "PROD_LIST_REQ"
export const PROD_LIST_SUCCESS = "PROD_LIST_SUCCESS";
export const PROD_LIST_FAIL = "PROD_LIST_FAIL";

export const PROD_DETAILS_REQ = "PROD_DETAILS_REQ";
export const PROD_DETAILS_SUCCESS = "PROD_DETAILS_SUCCESS";
export const PROD_DETAILS_FAIL = "PROD_DETAILS_FAIL";

export const PROD_DELETE_REQ = "PROD_DELETE_REQ";
export const PROD_DELETE_SUCCESS = "PROD_DELETE_SUCCESS";
export const PROD_DELETE_FAIL = "PROD_DELETE_FAIL";
