export const USER_LOGIN_REQ = "USER_LOGIN_REQ"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REG_REQ = "USER_REG_REQ";
export const USER_REG_SUCCESS = "USER_REG_SUCCESS";
export const USER_REG_FAIL = "USER_REG_FAIL";

export const USER_PROF_REQ = "USER_PROF_REQ";
export const USER_PROF_SUCCESS = "USER_PROF_SUCCESS";
export const USER_PROF_FAIL = "USER_PROF_FAIL";
export const USER_PROF_RESET = "USER_PROF_RESET";

export const USER_UPDATE_PROF_REQ = "USER_UPDATE_PROF_REQ";
export const USER_UPDATE_PROF_SUCCESS = "USER_UPDATE_PROF_SUCCESS";
export const USER_UPDATE_PROF_FAIL = "USER_UPDATE_PROF_FAIL";
export const USER_UPDATE_PROF_RESET = "USER_UPDATE_PROF_RESET";

export const USER_LIST_REQ = "USER_LIST_REQ";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_DELETE_REQ = "USER_DELETE_REQ";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const USER_UPDATE_REQ = "USER_UPDATE_REQ";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";